# just a script to test some things independently before putting them in the
# main script

CC=g++
CFLAGS = -Wall -std=c++11

all: prog

#prog:
#	$(CC) $(CFLAGS) R_to_temp.cpp

prog:
	$(CC) $(CFLAGS) cliMenu2cpp

clean:
	rm *.out

.PHONY: clean, prog, prog2, all
